# Stateful set is suitable to create master-slave topology, which can be used by databases
#  the serviceName is used to create a name for the pods. This case mysql-0 is the master mysql-1 is the first slave etc.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  # except for these fields they are the same like in a Deployment
  serviceName: mysql-h
  volumeClaimTemplates:
    - metadata:
        name: mysql-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi