apiVersion: v1
kind: Pod
metadata:
  name: math-pod
spec:
  containers:
    - name: math-add
      image: ubuntu
      command: [ 'expr', '3', '+', '2' ]
  # default restartPolicy: Always, not good for scheduled and cron jobs
  restartPolicy: Never