apiVersion: v1
items:
  kind: List
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: ingress-role
      namespace: ingress-space
    rules:
      - apiGroups:
          - ""
        resources:
          - configmaps
          - pods
          - secrets
          - namespaces
        verbs:
          - get
      - apiGroups:
          - ""
        resourceNames:
          - ingress-controller-leader-nginx
        resources:
          - configmaps
        verbs:
          - get
          - update
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - create
      - apiGroups:
          - ""
        resources:
          - endpoints
        verbs:
          - get
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: ingress-role-binding
      namespace: ingress-space
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: ingress-role
    subjects:
      - kind: ServiceAccount
        name: ingress-serviceaccount
