apiVersion: v1
kind: Service
metadata:
  name: back-en
spec:
  # Not compulsory, ClusterIP is the default type
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: myapp
    type: back-end